apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capture.fullname" . }}-secret
  labels:
{{ include "capture.labels" . | indent 4 }}
type: Opaque
stringData:
  API_SECRET: {{ .Values.secret.apiSecret | quote }}
