apiVersion: v1
kind: Service
metadata:
  name: {{ include "capture.fullname" . }}
  labels:
{{ include "capture.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "capture.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
