name: go

on:
  pull_request:
    branches:
      - main
      - develop

concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, ubuntu-24.04-arm, macos-15, windows-2025]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run all tests
        run: go test -v -timeout 30s ./test/...

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, ubuntu-24.04-arm, macos-15, windows-2025]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build capture binary
        run: go build -o dist/capture ./cmd/capture/
